### ISSUE TITLE
mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'

### ISSUE THREAD

**Issue by changyongyong** [supercoderlee/node-pyrunner#4]
Traceback (most recent call last):
  File "/Users/changyong/workspace/github/system-monitor/pyscript/app.py", line 4, in <module>
    import psutil
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/__init__.py", line 123, in <module>
    from . import _psosx as _psplatform
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psosx.py", line 13, in <module>
    from . import _psposix
  File "/opt/homebrew/lib/python3.9/site-packages/psutil/_psposix.py", line 28, in <module>
    from . import _psutil_osx
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (no such file), '/opt/homebrew/lib/python3.9/site-packages/psutil/_psutil_osx.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

可以支持下mac的自研芯片arm吗

**Comment by hileez** [comment]
@changyongyong Arm架构macos系统目前还没有适配，可能要过段时间。

**Comment by changyongyong** [comment]
> @changyongyong Arm架构macos系统目前还没有适配，可能要过段时间。

期待，我现在都是python开个socket服务，node和python通过socket交互，维护特别麻烦
