### ISSUE TITLE
windows10，提示找不到pyrunner.node模块

### ISSUE THREAD

**Issue by yushuohuanxiu** [supercoderlee/node-pyrunner#6]
return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The specified module could not be found.
\\?\c:\Users\moons\code\node-python-demo\node_modules\node-pyrunner\addons\3.10.10\win32\x64\pyrunner.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at new PyRunner (c:\Users\moons\code\node-python-demo\node_modules\node-pyrunner\index.js:49:23)
    at Object.<anonymous> (c:\Users\moons\code\node-python-demo\node_modules\node-pyrunner\index.js:140:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by yushuohuanxiu** [comment]
实际c:\Users\moons\code\node-python-demo\node_modules\node-pyrunner\addons\3.10.10\win32\x64\pyrunner.node文件是存在的

**Comment by hileez** [comment]
没有看到你的源码，但应该是没能加载到解释器的动态链接库，请拷贝动态链接库到项目目录后再测试。[Dynamic link library](https://github.com/supercoderlee/node-pyrunner#dynamic-link-library--%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93)
