### ISSUE TITLE
Library not loaded: '/Users/coderlee/.pyenv/versions/3.10.10/lib/libpython3.10.dylib'

### ISSUE THREAD

**Issue by wangBlue** [supercoderlee/node-pyrunner#8]
Library not loaded: '/Users/coderlee/.pyenv/versions/3.10.10/lib/libpython3.10.dylib'
  Referenced from: '/Users/xxx/Desktop/xxxx/xxxxx/node-pyrunner/node-pyrunner-quick-start/node_modules/node-pyrunner/addons/3.10.10/darwin/x64/pyrunner.node'
  Reason: tried: '/Users/coderlee/.pyenv/versions/3.10.10/lib/libpython3.10.dylib' (no such file), '/usr/local/lib/libpython3.10.dylib' (no such file), '/usr/lib/libpython3.10.dylib' (no such file)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at new PyRunner (/Users/xxx/xxx/xxxx/xxx/node-pyrunner/node-pyrunner-quick-start/node_modules/node-pyrunner/index.js:49:23)
    at Object.<anonymous> (/Users/xxx/xxx/xxx/xxxx/node-pyrunner/node-pyrunner-quick-start/node_modules/node-pyrunner/index.js:140:18)

**Comment by wangBlue** [comment]
这个mac系统里面动态库也放到根目录了 但是找的时候一直不对，是需要哪里在配置路径么？

**Comment by supercoderlee** [comment]
如果可以请把你使用node-pyrunner的代码段贴出来。

**Comment by hileez** [comment]
@wangBlue 如果可以请把你使用node-pyrunner的代码段贴出来。

**Comment by MrsignzZ** [comment]
相同问题
